version: "3"
services:
  fake-cam-1:
    restart: always
    image: ullaakut/rtspatt
    ports: 
      - "8554:8554"
    environment: 
      - INPUT=/tmp/video.mp4
    volumes: 
      - ./RTSPAllTheThings/samples/video.mp4:/tmp/video.mp4
    deploy:
      resources:
        limits:
          memory: 500M
  fake-cam-2:
    restart: always
    image: ullaakut/rtspatt
    ports: 
      - "8555:8554"
    environment: 
      - INPUT=/tmp/video.mp4
    volumes: 
      - ./RTSPAllTheThings/samples/video2.mp4:/tmp/video.mp4
    deploy:
      resources:
        limits:
          memory: 500M
  fake-cam-3:
    restart: always
    image: ullaakut/rtspatt
    ports: 
      - "8556:8554"
    environment: 
      - INPUT=/tmp/video.mp4
    volumes: 
      - ./RTSPAllTheThings/samples/kyle.mp4:/tmp/video.mp4
    deploy:
      resources:
        limits:
          memory: 500M