apiVersion: batch/v1
kind: Job
metadata:
  name: pull-video
spec:
  template:
    metadata:
      name: pull-video
    spec:
      containers:
        - name: pull-video
          image: truonghdpk/pull-fake-video:techainer
          volumeMounts:
            - name: video
              mountPath: /samples-mount
          command: [ "cp","-r", ".", "/samples" ]
          # command: [ "tail","-f", "/dev/null"]

      restartPolicy: Never

      volumes:
      - name: video
        persistentVolumeClaim:
          claimName: rtsp-relay-claim