apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rtsp-relay-claim
  name: rtsp-relay-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
