apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rtsp-relay
  name: rtsp-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-relay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rtsp-relay
    spec:
      containers:
        - env:
            - name: SOURCE_URL
              value: file:///samples/1.techainer-line-up.mp4
          image: flaviostutz/rtsp-relay
          name: rtsp-relay
          command:
            - "tail"
            - "-f"
            - "/dev/null"
          ports:
            - containerPort: 8554
          resources:
            limits:
              memory: "1G"
              cpu: "0"
          volumeMounts:
            - mountPath: /samples
              name: rtsp-relay-claim
      restartPolicy: Always
      volumes:
        - name: rtsp-relay-claim
          persistentVolumeClaim:
            claimName: rtsp-relay-claim
status: {}
